<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OutletControl.Contracts\OutletControl.Contracts.csproj" />
    <ProjectReference Include="..\OutletControl.Domain\OutletControl.Domain.csproj" />
  </ItemGroup>

</Project>
